

desc dept
desc emp
desc salgrade


SELECT EMPNO, ENAME, SAL, DEPTNO
FROM EMP
WHERE SAL > 1400
ORDER BY ENAME;

-- departamentele situate in CHICAGO
SELECT * FROM DEPT 
WHERE LOC='CHICAGO';

-- angajatii care au sef pe angajatul cu id-ul 7902 ( 7910), ordonate dupa salariu, descendent
SELECT * FROM EMP
WHERE
MGR=7902
ORDER BY SAL DESC;


SELECT * FROM EMP
WHERE
MGR=7910
or
MGR=7902
ORDER BY SAL DESC;


CREATE TABLE ANGAJAT_CU_A
AS
SELECT ENAME, EMPNO, SAL, DEPTNO
FROM EMP
WHERE
ENAME LIKE 'A%';

SELECT * FROM ANGAJAT_CU_A;


SELECT * FROM EMP 
WHERE 
 SAL >1000;


CREATE TABLE ANGAJATI_PESTE1000
AS
SELECT ENAME, EMPNO, SAL FROM EMP 
WHERE 
 SAL >1000;


SELECT * FROM ANGAJATI_PESTE1000;

-- TABELA CONTINAND TOTI SUBORDONATII ANGAJATULUI CU ID-UL 7839

CREATE TABLE SUBORDO
AS
SELECT ENAME, EMPNO, SAL, DEPTNO
FROM EMP
WHERE
MGR=7839;

SELECT * FROM SUBORDO;
DROP TABLE SUBORDO;

-- Comparatie pe date. Selectati angajatii ce au venit in firma dupa data de 01-martie-1981
SELECT * 
FROM EMP
WHERE
 HIREDATE > TO_DATE('01-03-1981', 'DD-MM-YYYY');

-- Angajatii veniti in firma in data de 20 feb 1981
select * from emp where to_char(hiredate, 'DD-MM-YYYY') ='20-02-1981';


-- In anii 80
select * from emp where to_char(hiredate, 'MM-YYYY') LIKE '02-1981';



SELECT * FROM  EMP
WHERE
TO_CHAR(HIREDATE,'YYYYMMDD') BETWEEN '19810402' AND '19811202';

-- ANGAJATII CARE NU AU COMISION
SELECT * FROM EMP WHERE COMM=NULL;

SELECT * FROM EMP WHERE COMM IS NULL;

SELECT * FROM EMP WHERE COMM IS NOT NULL;

-- ANGAJATII CU NUMELE CONTINAND SIRUL 'AR'
SELECT * FROM EMP WHERE ENAME LIKE '%AR%';


SELECT 'AZI ESTE DATA ', SYSDATE, EMPNO, SAL FROM EMP WHERE SAL >1500;

SELECT 'ANGAJATUL CU ID '|| EMPNO || ' A FOST ANGAJAT IN DATA DE '|| HIREDATE FROM EMP WHERE SAL >1500;

-- ANGAJATII CARE FAC PARTE DIN DEPARTAMENTUL CU LOCATIA IN CHICAGO
SELECT EMP.EMPNO, EMP.SAL, EMP.ENAME 
FROM EMP, DEPT
WHERE
 EMP.DEPTNO=DEPT.DEPTNO
 AND
 DEPT.LOC='CHICAGO';

SELECT A.EMPNO, A.ENAME FROM EMP A, EMP S WHERE A.MGR=S.EMPNO AND S.ENAME='KING';

SELECT COUNT(*) FROM EMP;




DROP TABLE ANGAJATI_PESTE1000;
